#!/usr/bin/env bash
# pyLuci - UserBot
# Copyright (C) 2021-2022 Lucifer
#
# This file is a part of < https://github.com/jonesroot/pyLuci/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamUltroid/Ultroid/blob/main/LICENSE/>.

git pull
echo "
            █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
            █░░╦─╦╔╗╦─╔╗╔╗╔╦╗╔╗░░█
            █░░║║║╠─║─║─║║║║║╠─░░█
            █░░╚╩╝╚╝╚╝╚╝╚╝╩─╩╚╝░░█
            █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█

      

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi


python3 app.py && \
python3 -m pyLuci
